# Generated by Django 5.2.7 on 2025-10-28 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('carrera', models.CharField(blank=True, max_length=100, null=True)),
                ('grado', models.IntegerField()),
            ],
        ),
    ]
