# Generated by Django 5.2.7 on 2025-10-28 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='grado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
