# Generated by Django 5.2.1 on 2025-11-05 18:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_estudiante_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='dia_pago',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31)], default=1, verbose_name='Día de Pago'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='direccion',
            field=models.CharField(default='Sin dirección', max_length=200, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='fecha_inicio',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Inicio'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='telefono',
            field=models.CharField(default='000000000', max_length=9, verbose_name='Teléfono del Estudiante'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='telefono_apoderado',
            field=models.CharField(default='000000000', max_length=9, verbose_name='Teléfono del Apoderado'),
        ),
    ]
